sonar.host.url=https://sonarcloud.io
sonar.organization=interbank
sonar.projectKey=ibk-crypto
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/cmd/**
sonar.tests=.
sonar.test.inclusions=**/*.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/sonar-report.xml
